# Generated by Django 6.0.2 on 2026-03-06 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('order_number', models.CharField(max_length=50, verbose_name='Order Number')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('subtotal', models.DecimalField(decimal_places=2, default='0', max_digits=12, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default='0', max_digits=12, verbose_name='Tax Amount')),
                ('total', models.DecimalField(decimal_places=2, default='0', max_digits=12, verbose_name='Total')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Shipping Address')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'ecommerce_onlineorder',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('store_name', models.CharField(blank=True, max_length=255, verbose_name='Store Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Currency')),
                ('allow_guest_checkout', models.BooleanField(default=True, verbose_name='Allow Guest Checkout')),
            ],
            options={
                'verbose_name': 'StoreSettings',
                'verbose_name_plural': 'StoreSettings',
                'db_table': 'ecommerce_storesettings',
                'abstract': False,
            },
        ),
    ]
